// <auto-generated />
using System;
using HotelManagementService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelManagementService.Infrastructure.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelManagementService.Core.Entities.Amenities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9738),
                            Name = "AC"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9741),
                            Name = "Balcony"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9744),
                            Name = "Coffee Maker"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9746),
                            Name = "Hair Dryer"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9749),
                            Name = "Jacuzzi"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9752),
                            Name = "Mini Bar"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9754),
                            Name = "Room Service"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9757),
                            Name = "Safe"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9759),
                            Name = "TV"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9762),
                            Name = "WiFi"
                        });
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("GuestId")
                        .HasColumnType("integer");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 938, DateTimeKind.Utc).AddTicks(7),
                            CreatedBy = "Admin",
                            Name = "Restuarant"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 938, DateTimeKind.Utc).AddTicks(10),
                            CreatedBy = "Admin",
                            Name = "House Keeping"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 938, DateTimeKind.Utc).AddTicks(13),
                            CreatedBy = "Admin",
                            Name = "Front Office"
                        });
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 938, DateTimeKind.Utc).AddTicks(166),
                            CreatedBy = "Admin",
                            DepartmentId = 1,
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 938, DateTimeKind.Utc).AddTicks(170),
                            CreatedBy = "Admin",
                            DepartmentId = 2,
                            FirstName = "Mary",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 938, DateTimeKind.Utc).AddTicks(174),
                            CreatedBy = "Admin",
                            DepartmentId = 3,
                            FirstName = "Sarah",
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 938, DateTimeKind.Utc).AddTicks(177),
                            CreatedBy = "Admin",
                            DepartmentId = 2,
                            FirstName = "Tracy",
                            LastName = "Morgan"
                        });
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IDNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.GuestPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("GuestId")
                        .HasColumnType("integer");

                    b.Property<int>("PreferenceId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("PreferenceId");

                    b.ToTable("GuestPreferences");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StarRating")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "City", "Country")
                        .IsUnique();

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main Street, CBD",
                            City = "",
                            Country = "",
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9392),
                            IsActive = true,
                            Name = "Grand Hotel",
                            StarRating = 0
                        });
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<int>("ReservationId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("integer");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.InvoiceLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceLineItems");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("HotelId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.Preferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Preferences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9948),
                            Name = "Non-smoking"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9951),
                            Name = "Early checkin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9953),
                            Name = "High floor"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9955),
                            Name = "Newspaper"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9957),
                            Name = "Late checkout"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9959),
                            Name = "Quiet room"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9961),
                            Name = "Room service"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9963),
                            Name = "Extra towels"
                        });
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Guests")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReservationSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("SpecialRequests")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.RestaurantOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("GuestId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("integer");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TableId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("TableId");

                    b.ToTable("RestaurantOrders");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.RestaurantTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("HotelId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TableNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("RestaurantTables");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("HotelId")
                        .HasColumnType("integer");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9598),
                            HotelId = 1,
                            RoomNumber = "101",
                            RoomTypeId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9642),
                            HotelId = 1,
                            RoomNumber = "102",
                            RoomTypeId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9646),
                            HotelId = 1,
                            RoomNumber = "201",
                            RoomTypeId = 3,
                            Status = 1
                        });
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.RoomAmenities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmenitiesId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AmenitiesId");

                    b.ToTable("RoomAmenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmenitiesId = 9,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9838),
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 2,
                            AmenitiesId = 1,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9841),
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            AmenitiesId = 10,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9844),
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            AmenitiesId = 7,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9847),
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            AmenitiesId = 9,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9849),
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            AmenitiesId = 9,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9852),
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 7,
                            AmenitiesId = 10,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9855),
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            AmenitiesId = 7,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9857),
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 9,
                            AmenitiesId = 1,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9860),
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            AmenitiesId = 3,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9863),
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 11,
                            AmenitiesId = 1,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9865),
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 12,
                            AmenitiesId = 2,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9868),
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 13,
                            AmenitiesId = 3,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9870),
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 14,
                            AmenitiesId = 4,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9873),
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 15,
                            AmenitiesId = 5,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9875),
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 16,
                            AmenitiesId = 6,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9878),
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 17,
                            AmenitiesId = 7,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9880),
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 18,
                            AmenitiesId = 8,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9883),
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 19,
                            AmenitiesId = 9,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9886),
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 20,
                            AmenitiesId = 10,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9888),
                            RoomTypeId = 3
                        });
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9540),
                            CreatedBy = "admin",
                            Price = 100.00m,
                            Type = "Standard"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 4,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9545),
                            CreatedBy = "admin",
                            Price = 150.00m,
                            Type = "Delux"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 6,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9549),
                            CreatedBy = "admin",
                            Price = 300.00m,
                            Type = "Standard"
                        });
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HotelId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TaskTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoomId");

                    b.HasIndex("TaskTypeId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.TaskType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("TaskTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 938, DateTimeKind.Utc).AddTicks(218),
                            CreatedBy = "Admin",
                            Name = "HouseKeeping",
                            Title = "House Keeping"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 938, DateTimeKind.Utc).AddTicks(222),
                            CreatedBy = "Admin",
                            Name = "Maintenance",
                            Title = "Maintenance"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 938, DateTimeKind.Utc).AddTicks(229),
                            CreatedBy = "Admin",
                            Name = "FrontDesk",
                            Title = "Front Desk"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 938, DateTimeKind.Utc).AddTicks(232),
                            CreatedBy = "Admin",
                            Name = "Restaurant",
                            Title = "Restaurant"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 938, DateTimeKind.Utc).AddTicks(235),
                            CreatedBy = "Admin",
                            Name = "Administration",
                            Title = "Administration"
                        });
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9693),
                            Email = "admin@hotel.com",
                            Name = "Admin User",
                            PasswordHash = "$2a$11$hash",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 19, 20, 59, 58, 937, DateTimeKind.Utc).AddTicks(9696),
                            Email = "staff@hotel.com",
                            Name = "Staff Member",
                            PasswordHash = "$2a$11$hash",
                            Role = "Staff"
                        });
                });

            modelBuilder.Entity("RoomAmenitiesRoomType", b =>
                {
                    b.Property<int>("AmenitiesId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomTypesId")
                        .HasColumnType("integer");

                    b.HasKey("AmenitiesId", "RoomTypesId");

                    b.HasIndex("RoomTypesId");

                    b.ToTable("RoomAmenitiesRoomType");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.Booking", b =>
                {
                    b.HasOne("HotelManagementService.Core.Entities.Guest", "Guest")
                        .WithMany("Bookings")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagementService.Core.Entities.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId");

                    b.HasOne("HotelManagementService.Core.Entities.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId");

                    b.HasOne("HotelManagementService.Core.Entities.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Invoice");

                    b.Navigation("Payment");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.Employee", b =>
                {
                    b.HasOne("HotelManagementService.Core.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.GuestPreferences", b =>
                {
                    b.HasOne("HotelManagementService.Core.Entities.Guest", "Guest")
                        .WithMany("GuestPreferences")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagementService.Core.Entities.Preferences", "Preferences")
                        .WithMany()
                        .HasForeignKey("PreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.InvoiceLineItem", b =>
                {
                    b.HasOne("HotelManagementService.Core.Entities.Invoice", "Invoice")
                        .WithMany("LineItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.MenuItem", b =>
                {
                    b.HasOne("HotelManagementService.Core.Entities.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("HotelManagementService.Core.Entities.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagementService.Core.Entities.RestaurantOrder", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.Payment", b =>
                {
                    b.HasOne("HotelManagementService.Core.Entities.Invoice", null)
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.Reservation", b =>
                {
                    b.HasOne("HotelManagementService.Core.Entities.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.RestaurantOrder", b =>
                {
                    b.HasOne("HotelManagementService.Core.Entities.Guest", "Guest")
                        .WithMany("RestaurantOrders")
                        .HasForeignKey("GuestId");

                    b.HasOne("HotelManagementService.Core.Entities.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId");

                    b.HasOne("HotelManagementService.Core.Entities.RestaurantTable", "Table")
                        .WithMany("Orders")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Reservation");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.RestaurantTable", b =>
                {
                    b.HasOne("HotelManagementService.Core.Entities.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.Room", b =>
                {
                    b.HasOne("HotelManagementService.Core.Entities.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagementService.Core.Entities.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.RoomAmenities", b =>
                {
                    b.HasOne("HotelManagementService.Core.Entities.Amenities", "Amenities")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("AmenitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenities");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.TaskItem", b =>
                {
                    b.HasOne("HotelManagementService.Core.Entities.Employee", "AssignedTo")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedToId");

                    b.HasOne("HotelManagementService.Core.Entities.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagementService.Core.Entities.Room", "Room")
                        .WithMany("TaskItems")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagementService.Core.Entities.TaskType", "TaskType")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("Hotel");

                    b.Navigation("Room");

                    b.Navigation("TaskType");
                });

            modelBuilder.Entity("RoomAmenitiesRoomType", b =>
                {
                    b.HasOne("HotelManagementService.Core.Entities.RoomAmenities", null)
                        .WithMany()
                        .HasForeignKey("AmenitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagementService.Core.Entities.RoomType", null)
                        .WithMany()
                        .HasForeignKey("RoomTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.Amenities", b =>
                {
                    b.Navigation("RoomAmenities");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.Employee", b =>
                {
                    b.Navigation("AssignedTasks");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.Guest", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("GuestPreferences");

                    b.Navigation("RestaurantOrders");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.Invoice", b =>
                {
                    b.Navigation("LineItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.MenuItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.RestaurantOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.RestaurantTable", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.Room", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reservations");

                    b.Navigation("TaskItems");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelManagementService.Core.Entities.TaskType", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
